blank_issues_enabled: true
contact_links:
  - name: Request Feature
    url: https://github.com/BuidlGuidl/abi.ninja/discussions/new?category=ideas
    about: Requests features or brainstorm ideas for new functionality
