name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/nextjs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Build Next.js app
        run: yarn build
      - name: Start Next.js app and run tests
        run: |
          yarn start & # Start in background
          echo "Waiting for Next.js to be ready..."
          # Wait up to 2 minutes for the server to be ready
          timeout=120
          while ! curl -s http://localhost:3000 > /dev/null; do
            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for Next.js to start"
              exit 1
            fi
            echo "Waiting for server... ($timeout seconds left)"
            timeout=$((timeout-5))
            sleep 5
          done
          echo "Server is ready!"
          yarn playwright test --debug
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/nextjs/playwright-report/
          retention-days: 30
